let data=
[{"cate":1,"hira":"おおきい","kanji":"大きい","kor":"크다"},
    {"cate":1,"hira":"ちいさい","kanji":"小さい","kor":"작다"},
    {"cate":1,"hira":"あたらしい","kanji":"新しい","kor":"새롭다"},
    {"cate":1,"hira":"ふるい","kanji":"古い","kor":"오래되다"},
    {"cate":1,"hira":"いい / よい","kanji":"良い（いい）","kor":"좋다"},
    {"cate":1,"hira":"わるい","kanji":"悪い","kor":"나쁘다"},
    {"cate":1,"hira":"あつい","kanji":"暑い","kor":"덥다 (날씨)"},
    {"cate":1,"hira":"さむい","kanji":"寒い","kor":"춥다"},
    {"cate":1,"hira":"あつい","kanji":"熱い","kor":"뜨겁다 (사물)"},
    {"cate":1,"hira":"つめたい","kanji":"冷たい","kor":"차갑다"},
    {"cate":1,"hira":"たかい","kanji":"高い","kor":"높다, 비싸다"},
    {"cate":1,"hira":"ひくい","kanji":"低い","kor":"낮다"},
    {"cate":1,"hira":"やすい","kanji":"安い","kor":"싸다"},
    {"cate":1,"hira":"ちかい","kanji":"近い","kor":"가깝다"},
    {"cate":1,"hira":"とおい","kanji":"遠い","kor":"멀다"},
    {"cate":1,"hira":"ながい","kanji":"長い","kor":"길다"},
    {"cate":1,"hira":"みじかい","kanji":"短い","kor":"짧다"},
    {"cate":1,"hira":"はやい","kanji":"早い","kor":"빠르다 (시간)"},
    {"cate":1,"hira":"おそい","kanji":"遅い","kor":"느리다, 늦다"},
    {"cate":1,"hira":"いそがしい","kanji":"忙しい","kor":"바쁘다"},
    {"cate":1,"hira":"たのしい","kanji":"楽しい","kor":"즐겁다"},
    {"cate":1,"hira":"おもしろい","kanji":"面白い","kor":"재미있다"},
    {"cate":1,"hira":"うるさい","kanji":"うるさい","kor":"시끄럽다, 성가시다"},
    {"cate":1,"hira":"やさしい","kanji":"優しい","kor":"상냥하다"},
    {"cate":1,"hira":"きびしい","kanji":"厳しい","kor":"엄격하다"},
    {"cate":1,"hira":"つよい","kanji":"強い","kor":"강하다"},
    {"cate":1,"hira":"よわい","kanji":"弱い","kor":"약하다"},
    {"cate":1,"hira":"あかるい","kanji":"明るい","kor":"밝다"},
    {"cate":1,"hira":"くらい","kanji":"暗い","kor":"어둡다"},
    {"cate":1,"hira":"あまい","kanji":"甘い","kor":"달다"},
    {"cate":1,"hira":"からい","kanji":"辛い","kor":"맵다"},
    {"cate":1,"hira":"にがい","kanji":"苦い","kor":"쓰다"},
    {"cate":1,"hira":"おもい","kanji":"重い","kor":"무겁다"},
    {"cate":1,"hira":"かるい","kanji":"軽い","kor":"가볍다"},
    {"cate":1,"hira":"かたい","kanji":"硬い","kor":"단단하다"},
    {"cate":1,"hira":"やわらかい","kanji":"柔らかい","kor":"부드럽다"},
    {"cate":1,"hira":"ただしい","kanji":"正しい","kor":"옳다, 정확하다"},
    {"cate":1,"hira":"わすれやすい","kanji":"忘れやすい","kor":"잘 잊는다"},
    {"cate":1,"hira":"おぼえにくい","kanji":"覚えにくい","kor":"외우기 어렵다"},
    {"cate":1,"hira":"すばらしい","kanji":"素晴らしい","kor":"훌륭하다"},
    {"cate":1,"hira":"はずかしい","kanji":"恥ずかしい","kor":"부끄럽다"},
    {"cate":1,"hira":"うつくしい","kanji":"美しい","kor":"아름답다"},
    {"cate":1,"hira":"さびしい","kanji":"寂しい","kor":"외롭다"},
    {"cate":1,"hira":"あつい","kanji":"厚い","kor":"두껍다"},
    {"cate":1,"hira":"うすい","kanji":"薄い","kor":"얇다"},
    {"cate":1,"hira":"こわい","kanji":"怖い","kor":"무섭다"},
    {"cate":1,"hira":"おかしい","kanji":"可笑しい","kor":"이상하다, 웃기다"},
    {"cate":2,"hira":"しずか","kanji":"静か","kor":"조용한"},
    {"cate":2,"hira":"げんき","kanji":"元気","kor":"건강한 / 활기찬"},
    {"cate":2,"hira":"しんせつ","kanji":"親切","kor":"친절한"},
    {"cate":2,"hira":"べんり","kanji":"便利","kor":"편리한"},
    {"cate":2,"hira":"ふべん","kanji":"不便","kor":"불편한"},
    {"cate":2,"hira":"たいせつ","kanji":"大切","kor":"소중한"},
    {"cate":2,"hira":"だいじょうぶ","kanji":"大丈夫","kor":"괜찮은"},
    {"cate":2,"hira":"かんたん","kanji":"簡単","kor":"간단한"},
    {"cate":2,"hira":"ふくざつ","kanji":"複雑","kor":"복잡한"},
    {"cate":2,"hira":"じょうず","kanji":"上手","kor":"능숙한"},
    {"cate":2,"hira":"へた","kanji":"下手","kor":"서투른"},
    {"cate":2,"hira":"すき","kanji":"好き","kor":"좋아하는"},
    {"cate":2,"hira":"じゆう","kanji":"自由","kor":"자유로운"},
    {"cate":2,"hira":"とくべつ","kanji":"特別","kor":"특별한"},
    {"cate":2,"hira":"きけん","kanji":"危険","kor":"위험한"},
    {"cate":2,"hira":"あんぜん","kanji":"安全","kor":"안전한"},
    {"cate":2,"hira":"しあわせ","kanji":"幸せ","kor":"행복한"},
    {"cate":2,"hira":"まじめ","kanji":"真面目","kor":"성실한"},
    {"cate":2,"hira":"てきとう","kanji":"適当","kor":"적당한, 대충한"},
    {"cate":2,"hira":"ひつよう","kanji":"必要","kor":"필요한"},
    {"cate":2,"hira":"かいてき","kanji":"快適","kor":"쾌적한"},
    {"cate":2,"hira":"しんせん","kanji":"新鮮","kor":"신선한"},
    {"cate":2,"hira":"にぎやか","kanji":"賑やか","kor":"번화한"},
    {"cate":2,"hira":"かんぜん","kanji":"完全","kor":"완전한"},
    {"cate":2,"hira":"けんこう","kanji":"健康","kor":"건강한"},
    {"cate":2,"hira":"たいへん","kanji":"大変","kor":"힘든, 큰일인"},
    {"cate":2,"hira":"へいわ","kanji":"平和","kor":"평화로운"},
    {"cate":2,"hira":"ゆうり","kanji":"有利","kor":"유리한"},
    {"cate":2,"hira":"ふり","kanji":"不利","kor":"불리한"},
    {"cate":2,"hira":"ゆたか","kanji":"豊か","kor":"풍요로운"},
    {"cate":2,"hira":"いっしょうけんめい","kanji":"一生懸命","kor":"열심인"},
    {"cate":2,"hira":"しょうじき","kanji":"正直","kor":"정직한"},
    {"cate":2,"hira":"せっきょくてき","kanji":"積極的","kor":"적극적인"},
    {"cate":2,"hira":"しょうきょくてき","kanji":"消極的","kor":"소극적인"},
    {"cate":2,"hira":"ゆうのう","kanji":"有能","kor":"유능한"}]